package com.balsdon.androidallyplugin.values

enum class TalkBackSetting {
    TOGGLE_SPEECH_OUTPUT,
    ECHO_RECOGNIZED_SPEECH,
    REDUCE_WINDOW_ANNOUNCEMENT_DELAY,
    ENABLE_PERFORMANCE_STATISTICS,
    EXPLORE_BY_TOUCH,
    NODE_TREE_DEBUGGING
}