name: Sign Plugin
on:
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Setup and execute Gradle 'signPlugin' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: signPlugin
        env:
          VERSION_NUMBER: ${{ env.VERSION_NUMBER }}-${{ github.run_number }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-ally-${{ env.VERSION_NUMBER }}-signed.zip
          path: ./build/distributions/android-ally-plugin-${{ env.VERSION_NUMBER }}-signed.zip