name: Sign Plugin
on:
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: ${{ vars.VERSION_NUMBER }}-${{ github.run_number }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Version details
        run: |          
          echo "INTERNAL VERSION : ${{ vars.VERSION_NUMBER }}"
          echo "GITHUB RUN NUMBER: ${{ github.run_number }}"
          echo "VERSION_NUMBER   : ${VERSION_NUMBER}"

      - name: Setup and execute Gradle 'signPlugin' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: signPlugin

      - name: Output details
        run: |          
          echo "Contents of ./build/distributions/"
          ls -1 ./build/distributions/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-ally-${VERSION_NUMBER}-signed.zip
          path: ./build/distributions/android-ally-plugin-${VERSION_NUMBER}-signed.zip
