name: Sign Plugin

#on: [workflow_dispatch]
on:
  pull_request:
    branches: [main]

jobs:
  sign-plugin:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: ${{ vars.VERSION_NUMBER }}-${{ github.run_number }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
      OUTPUT_DIR: ./build/distributions/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Version details
        run: |          
          echo "INTERNAL VERSION : ${{ vars.VERSION_NUMBER }}"
          echo "GITHUB RUN NUMBER: ${{ github.run_number }}"
          echo "VERSION_NUMBER   : ${VERSION_NUMBER}"

      - name: Setup and execute Gradle 'signPlugin' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: signPlugin

      - name: Output details
        run: |          
          echo "Contents of ${{ env.OUTPUT_DIR }}"
          ls -1 ${{ env.OUTPUT_DIR }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: android-ally-plugin-${{ env.VERSION_NUMBER }}
          path: ${{ env.OUTPUT_DIR }}/android-ally-plugin-${{ env.VERSION_NUMBER }}-signed.zip
          compression-level: 0 # no compression since this is zipped