name: Gradle Tests for PRs
on:
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Missing performanceTesting jar hack fix
        run: |
          echo "see https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1738"
          FOLDER=/home/runner/.gradle/caches/transforms-3/e773a64bc76e36769f59d43df2c66fa6/transformed/android-studio-2024.2.1.10-linux/plugins
          mkdir -p ${FOLDER}/performanceTesting
          mkdir -p ${FOLDER}/performanceTesting/lib

          FOLDER=${FOLDER}/performanceTesting/lib
          FILE=performance-testing-242.23339.19.jar
          URL=https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/${FILE}
          wget -O ${FOLDER}/${FILE} ${URL}
          ls -l ${FOLDER}

      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt test