name: Sign And Publish Plugin

on: [workflow_dispatch]

jobs:
  publish-plugin-to-marketplace:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: ${{ vars.VERSION_NUMBER }}-${{ github.run_number }}
      PUBLISH_TOKEN: ${{ secrets.PLUGIN_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
      PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
      OUTPUT_DIR: ./build/distributions/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Missing performanceTesting jar hack fix
        run: |
          echo "Temp fix for linux builds, see https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1738"
          FOLDER=/home/runner/.gradle/caches/transforms-3/e773a64bc76e36769f59d43df2c66fa6/transformed/android-studio-2024.2.1.10-linux/plugins
          mkdir -p ${FOLDER}/performanceTesting
          mkdir -p ${FOLDER}/performanceTesting/lib
  
          FOLDER=${FOLDER}/performanceTesting/lib
          FILE=performance-testing-242.23339.19.jar
          URL=https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/${FILE}
          wget ${URL}
          ls -l ${FOLDER}          

      - name: Version details
        run: |          
          echo "INTERNAL VERSION : ${{ vars.VERSION_NUMBER }}"
          echo "GITHUB RUN NUMBER: ${{ github.run_number }}"
          echo "VERSION_NUMBER   : ${VERSION_NUMBER}"

      - name: Setup and execute Gradle 'publishPlugin' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugin